name: Github Pages Astro CI

on:
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: |
          OUTPUT=$(npm run scrape)
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          echo $OUTPUT >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: Checkout your repository using git
        uses: actions/checkout@v2
      - name: Install, build, and upload your site
        uses: withastro/action@v0

  deploy:
    needs: fetch
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
