name: Scrape
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: |
          OUTPUT=$(npm run scrape)
          echo 'JSON_RESPONSE<<EOF' >> $GITHUB_ENV
          echo $OUTPUT >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
      - name: log
        run: echo ${{ env.JSON_RESPONSE }}
